version: '3.9'

networks:
  local:

services:

  quarkus:
    container_name: "quarkus"
    image: serrodcal/quarkus-monitoring-docker-compose:latest
    ports: 
      - "8080:8080"
    networks:
      - local

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.external-url=http://localhost:9090'
    ports:
      - "9090:9090"
    networks:
      - local
    depends_on: 
      - quarkus

  grafana:
    container_name: "grafana"
    image: grafana/grafana:8.1.3
    #user: "grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/jvm-quarkus-micrometer-metrics_rev6.json:/var/lib/grafana/dashboards/dashboard.json
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    networks:
      - local
    depends_on:
      - quarkus
      - prometheus